// <auto-generated />
using System;
using CarRentalApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRentalApi.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    partial class CarRentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarModelId")
                        .HasColumnType("integer");

                    b.Property<int>("CarTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("CarTypeId");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 1,
                            CarTypeId = 1,
                            IsRented = false,
                            PlateNumber = "ABC-1234"
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 2,
                            CarTypeId = 2,
                            IsRented = false,
                            PlateNumber = "DEF-5678"
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 4,
                            CarTypeId = 3,
                            IsRented = false,
                            PlateNumber = "GHI-9012"
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 5,
                            CarTypeId = 1,
                            IsRented = false,
                            PlateNumber = "JKL-3456"
                        },
                        new
                        {
                            Id = 5,
                            CarModelId = 3,
                            CarTypeId = 2,
                            IsRented = false,
                            PlateNumber = "MNO-7890"
                        },
                        new
                        {
                            Id = 6,
                            CarModelId = 6,
                            CarTypeId = 3,
                            IsRented = false,
                            PlateNumber = "PQR-2345"
                        });
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CarModel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BMW 7"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kia Sorento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nissan JuKe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Seat Ibiza"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audi A8"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Renault Clio"
                        });
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.CarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CarType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoyaltyPoints = 5,
                            Name = "Premium",
                            PricePerDay = 300.00m
                        },
                        new
                        {
                            Id = 2,
                            LoyaltyPoints = 3,
                            Name = "SUV",
                            PricePerDay = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            LoyaltyPoints = 1,
                            Name = "Small",
                            PricePerDay = 50.00m
                        });
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("LoyaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "John@gmail.com",
                            LoyaltyPoints = 0,
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jane@gmail.com",
                            LoyaltyPoints = 0,
                            Name = "Jane Smith",
                            PhoneNumber = "098-765-4321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Alice@gmail.com",
                            LoyaltyPoints = 0,
                            Name = "Alice Johnson",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Bob@gmail.com",
                            LoyaltyPoints = 0,
                            Name = "Bob Brown",
                            PhoneNumber = "444-987-6543"
                        });
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedDaysBooked")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraDaysBooked")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Surcharges")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Rental", (string)null);
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarRentalApi.Domain.Entities.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApi.Domain.Entities.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("CarType");
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Rental", b =>
                {
                    b.HasOne("CarRentalApi.Domain.Entities.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApi.Domain.Entities.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Car", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.CarType", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalApi.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
